/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author AAAQM
 */
public class Nodos extends javax.swing.JFrame {

    /**
     * Creates new form Nodos
     */
    public Nodos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Round_JWC3 = new swing.Btn_Round_JWC();
        panel_Round_JWC1 = new swing.Panel_Round_JWC();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panel_Round_JWC2 = new swing.Panel_Round_JWC();
        panel_Round_JWC3 = new swing.Panel_Round_JWC();
        img_Autosize_JWC1 = new swing.Img_Autosize_JWC();
        img_Autosize_JWC2 = new swing.Img_Autosize_JWC();
        panel_Round_JWC4 = new swing.Panel_Round_JWC();
        img_Autosize_JWC3 = new swing.Img_Autosize_JWC();
        btn_Round_JWC1 = new swing.Btn_Round_JWC();
        btn_Round_JWC2 = new swing.Btn_Round_JWC();
        btn_Round_JWC4 = new swing.Btn_Round_JWC();
        btn_Round_JWC5 = new swing.Btn_Round_JWC();

        btn_Round_JWC3.setBackground(new java.awt.Color(110, 195, 136));
        btn_Round_JWC3.setText("Punto a punto en menor distancia");
        btn_Round_JWC3.setArco_esquina(25);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_Round_JWC1.setBackground(new java.awt.Color(75, 112, 154));
        panel_Round_JWC1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("MSC Solutions");
        panel_Round_JWC1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("V 0.1");
        panel_Round_JWC1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 580, -1, -1));

        panel_Round_JWC2.setBackground(new java.awt.Color(221, 217, 199));

        panel_Round_JWC3.setBackground(new java.awt.Color(70, 73, 75));
        panel_Round_JWC3.setEsqInferiorDerecha(20);
        panel_Round_JWC3.setEsqInferiorIzquierda(20);
        panel_Round_JWC3.setEsqSuperiorDerecha(20);
        panel_Round_JWC3.setEsqSuperiorIzquierda(20);

        img_Autosize_JWC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Metro.png"))); // NOI18N

        javax.swing.GroupLayout panel_Round_JWC3Layout = new javax.swing.GroupLayout(panel_Round_JWC3);
        panel_Round_JWC3.setLayout(panel_Round_JWC3Layout);
        panel_Round_JWC3Layout.setHorizontalGroup(
            panel_Round_JWC3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_JWC3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img_Autosize_JWC1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_Round_JWC3Layout.setVerticalGroup(
            panel_Round_JWC3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Round_JWC3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img_Autosize_JWC1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_Round_JWC2Layout = new javax.swing.GroupLayout(panel_Round_JWC2);
        panel_Round_JWC2.setLayout(panel_Round_JWC2Layout);
        panel_Round_JWC2Layout.setHorizontalGroup(
            panel_Round_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_JWC2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_Round_JWC3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_Round_JWC2Layout.setVerticalGroup(
            panel_Round_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_JWC2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_Round_JWC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panel_Round_JWC1.add(panel_Round_JWC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 480, 610));

        img_Autosize_JWC2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo.png"))); // NOI18N
        panel_Round_JWC1.add(img_Autosize_JWC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 40, 40));

        panel_Round_JWC4.setBackground(new java.awt.Color(255, 255, 255));
        panel_Round_JWC4.setEsqInferiorDerecha(25);
        panel_Round_JWC4.setEsqSuperiorDerecha(25);

        img_Autosize_JWC3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/NYC.png"))); // NOI18N

        javax.swing.GroupLayout panel_Round_JWC4Layout = new javax.swing.GroupLayout(panel_Round_JWC4);
        panel_Round_JWC4.setLayout(panel_Round_JWC4Layout);
        panel_Round_JWC4Layout.setHorizontalGroup(
            panel_Round_JWC4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_JWC4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(img_Autosize_JWC3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        panel_Round_JWC4Layout.setVerticalGroup(
            panel_Round_JWC4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(img_Autosize_JWC3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        panel_Round_JWC1.add(panel_Round_JWC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 330, 50));

        btn_Round_JWC1.setBackground(new java.awt.Color(110, 195, 136));
        btn_Round_JWC1.setText("Recorrer todos los nodos ");
        btn_Round_JWC1.setArco_esquina(25);
        panel_Round_JWC1.add(btn_Round_JWC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 280, 50));

        btn_Round_JWC2.setBackground(new java.awt.Color(110, 195, 136));
        btn_Round_JWC2.setText("Punto a punto en menor distancia");
        btn_Round_JWC2.setArco_esquina(25);
        panel_Round_JWC1.add(btn_Round_JWC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 280, 50));

        btn_Round_JWC4.setBackground(new java.awt.Color(110, 195, 136));
        btn_Round_JWC4.setText("Punto a punto en menor tiempo ");
        btn_Round_JWC4.setArco_esquina(25);
        panel_Round_JWC1.add(btn_Round_JWC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 280, 50));

        btn_Round_JWC5.setBackground(new java.awt.Color(110, 195, 136));
        btn_Round_JWC5.setText("Punto a punto en menor costo ");
        btn_Round_JWC5.setArco_esquina(25);
        panel_Round_JWC1.add(btn_Round_JWC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 280, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Round_JWC1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Round_JWC1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nodos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Btn_Round_JWC btn_Round_JWC1;
    private swing.Btn_Round_JWC btn_Round_JWC2;
    private swing.Btn_Round_JWC btn_Round_JWC3;
    private swing.Btn_Round_JWC btn_Round_JWC4;
    private swing.Btn_Round_JWC btn_Round_JWC5;
    private swing.Img_Autosize_JWC img_Autosize_JWC1;
    private swing.Img_Autosize_JWC img_Autosize_JWC2;
    private swing.Img_Autosize_JWC img_Autosize_JWC3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private swing.Panel_Round_JWC panel_Round_JWC1;
    private swing.Panel_Round_JWC panel_Round_JWC2;
    private swing.Panel_Round_JWC panel_Round_JWC3;
    private swing.Panel_Round_JWC panel_Round_JWC4;
    // End of variables declaration//GEN-END:variables
}
